### ISSUE TITLE
Awesome project!

### ISSUE THREAD

**Issue by yuchi** [CureApp/tisomorphic#1]
Hi @shinout, creator and maintainer of _Titaniumifier_ here!

Great project, I love to see _Titaniumifier_ in the wild! We at @smclab did work on [something very similar and called it Host-mode](https://github.com/smclab/titaniumifier/wiki/Host-mode).

Would love some feedback over it and, if you wish, consider merging the two projects together.

**Comment by shinout** [comment]
Thanks @yuchi. I love Titaniumifier.

Titaniumifier is no doubt great work, but I'd like it to be simpler. I just want the functionality of packing modules into one js file. Then we will re-use it as we like. Every titanium project has its own circumstances and the best solution to be isomorphic would differ. For our projects, _tisomorphic_ is the best solution.

Of course we need better titanium framework (requiring system, testing, fast building and so on...). Other project of yours seem interesting. Let's get titanium more useful and more popular!

**Comment by yuchi** [comment]
By the way, I believe you don’t need to use your own flavour of _titaniumifier_ anymore. We should have merged your changes in the latest version.

**Comment by shinout** [comment]
OK, I'll merge your project.

**Comment by yuchi** [comment]
Closing for obsolescence
